// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsetzulgbfupzigfijgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZXR6dWxnYmZ1cHppZ2ZpamdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzAwMDksImV4cCI6MjA3MDMwNjAwOX0.IJ3xRp4Gxajk4LnAC9HpoL_eeFsrXWcQOpN3PaHX2Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});